export const DEPARTMENT_ROOMS = {
  dashboard: {
    id: "dashboard",
    label: "Dashboard",
    agent: {
      id: "luca",
      name: "Luca",
      role: "Amministratore Delegato AI",
      avatar: "/agents/luca.jpg",
      initials: "L",
      accent: "bg-slate-900 text-yellow-400",
      chat: "luca",
      prompt: "Fammi il briefing CEO di oggi e dimmi dove devo intervenire.",
    },
    metrics: [
      "Fatturato mese",
      "Partnership chiuse",
      "Partner attivi",
      "Partner bloccati",
      "Azioni per Claudio",
      "Reparto critico",
    ],
    briefing: {
      numbers: "Fotografia generale: entrate, partner attivi, blocchi e decisioni aperte.",
      working: "Il CRM ordina i reparti per funzione: acquisizione, vendite, delivery, casi studio e back office.",
      notWorking: "Il rischio principale e' disperdere attenzione in troppe schermate non prioritarie.",
      solution: "Guarda prima le azioni che richiedono Claudio, poi il reparto piu' critico, poi le card operative.",
      note: "Ogni numero deve servire a una decisione. Se non cambia una scelta, resta fuori dalla dashboard.",
    },
    priorities: ["Sblocca le decisioni rosse", "Controlla il reparto critico", "Verifica avanzamento partner e vendite"],
  },
  acquisizione: {
    id: "acquisizione",
    label: "Acquisizione",
    agent: {
      id: "luca",
      name: "Luca",
      role: "Coordinatore Acquisizione Evolution",
      avatar: "/agents/luca.jpg",
      initials: "L",
      chat: "luca",
      prompt: "Luca, dimmi quali messaggi stanno portando lead giusti e dove devo intervenire oggi su Acquisizione Evolution.",
    },
    metrics: [
      "Nuovi lead 7 giorni",
      "Lead qualificati",
      "Masterclass avviate",
      "8 Domande completate",
      "Ciak Start €499",
      "Blueprint acquistati",
      "Fonte migliore",
    ],
    briefing: {
      numbers: "Misura la catena contenuto -> lead -> masterclass -> 8 Domande -> Blueprint.",
      working: "Funziona cio' che porta persone adatte alla Partnership, non cio' che fa solo volume.",
      notWorking: "Se arrivano curiosi non qualificati, il messaggio sta promettendo la cosa sbagliata.",
      solution: "Spingi il canale che produce Blueprint, recupera chi ha completato le 8 Domande, correggi l'hook piu' debole.",
      note: "Niente vanity metrics: like e visualizzazioni contano solo se muovono la pipeline.",
    },
    priorities: [
      "20 nuovi contatti mirati",
      "Recuperi Blueprint e call",
      "Contenuto Claudio con CTA Ciak",
    ],
    prompts: [
      {
        label: "Priorita' del giorno",
        prompt: "Luca, dimmi quali contatti lavorare oggi per Acquisizione Evolution.",
      },
      {
        label: "Recuperi caldi",
        prompt: "Luca, trova chi ha cliccato checkout, completato le 8 Domande o acquistato Blueprint senza call.",
      },
      {
        label: "Contenuto acquisizione",
        prompt: "Andrea, prepara un contenuto Claudio che porti professionisti reali verso Ciak Blueprint.",
      },
    ],
  },
  vendite: {
    id: "vendite",
    label: "Vendite",
    agent: {
      id: "gaia",
      name: "Gaia",
      role: "Responsabile Vendite",
      avatar: "/agents/gaia.jpg",
      initials: "G",
      chat: "pending",
      prompt: "Gaia, dimmi dove stiamo perdendo partner pronti a comprare.",
    },
    metrics: [
      "Blueprint acquistati",
      "Call prenotate",
      "Call fatte",
      "Proposte inviate",
      "Ciak Start €499",
      "Partnership chiuse",
      "Valore trattative",
    ],
    briefing: {
      numbers: "Segui il passaggio da interesse qualificato a proposta e chiusura Partnership.",
      working: "Funziona quando call, proposta e follow-up hanno una prossima azione chiara.",
      notWorking: "Il rischio e' perdere prospect caldi dopo la call o lasciare proposte senza inseguimento.",
      solution: "Controlla call fatte senza esito, proposte inviate non viste e trattative con valore alto.",
      note: "Ogni prospect caldo deve avere una prossima mossa e una data.",
    },
    priorities: ["Follow-up call fatte", "Proposte ferme", "Recuperi ad alto valore"],
  },
  delivery: {
    id: "delivery",
    label: "Delivery",
    agent: {
      id: "stefania",
      name: "Simona",
      role: "Responsabile Delivery",
      avatar: "/agents/stefania.jpg",
      initials: "S",
      chat: "stefania",
      prompt: "Simona, dimmi chi rischio di rallentare o perdere oggi.",
    },
    metrics: [
      "Partner attivi",
      "Partner per fase",
      "Fermi oltre soglia",
      "Output da approvare",
      "Materiali mancanti",
      "Prossimi live",
    ],
    briefing: {
      numbers: "La Delivery deve mostrare chi avanza, chi e' fermo e cosa blocca il prossimo output.",
      working: "Funziona quando ogni partner ha una sola prossima azione chiara.",
      notWorking: "Il rischio e' che Claudio diventi il collo di bottiglia per file, approvazioni e solleciti.",
      solution: "Parti da Serve Claudio, poi Serve Partner, poi In revisione. Automatizza solleciti e preparazione approvazioni.",
      note: "Chiedi intervento umano solo per decisione, relazione o scelta strategica fuori standard.",
    },
    priorities: ["Partner fermi", "Materiali da approvare", "Solleciti automatici"],
  },
  "casi-studio": {
    id: "casi-studio",
    label: "Casi studio",
    agent: {
      id: "andrea",
      name: "Andrea",
      role: "Responsabile Prova Sociale",
      avatar: "/agents/andrea.jpg",
      initials: "A",
      chat: "pending",
      prompt: "Andrea, quali risultati possiamo trasformare in fiducia per vendere meglio?",
    },
    metrics: [
      "Risultati documentabili",
      "Casi pronti",
      "Casi promettenti",
      "Asset mancanti",
      "Testimonianze",
      "Prima/dopo",
    ],
    briefing: {
      numbers: "Conta solo cio' che puo' diventare prova sociale concreta.",
      working: "Funzionano casi con numero, contesto, prima/dopo e prova verificabile.",
      notWorking: "Un risultato senza asset o storia e' difficile da usare nel funnel.",
      solution: "Raccogli screenshot, testimonianza e contesto dai partner piu' promettenti.",
      note: "Il caso studio deve aiutare Vendite e Marketing, non essere un archivio celebrativo.",
    },
    priorities: ["Caso piu' forte", "Asset mancanti", "Partner da intervistare"],
  },
  "back-office": {
    id: "back-office",
    label: "Back office",
    agent: {
      id: "valentina",
      name: "Valentina",
      role: "Responsabile Back Office",
      avatar: "/agents/valentina.jpg",
      initials: "V",
      chat: "pending",
      prompt: "Valentina, dimmi cosa puo' bloccare incasso, contratto o serenita operativa.",
    },
    metrics: [
      "Incassi mese",
      "Fatture da emettere",
      "Contratti firmati",
      "Documenti mancanti",
      "Pagamenti critici",
      "Servizi extra",
    ],
    briefing: {
      numbers: "Tieni sotto controllo soldi, contratti, fatture, accessi e rischi amministrativi.",
      working: "Funziona quando ogni vendita genera subito fattura, accesso e stato contratto coerenti.",
      notWorking: "Il rischio e' scoprire tardi dati fiscali, rate, contratti o accessi mancanti.",
      solution: "Controlla da fatturare, contratti da sistemare, pagamenti critici e accessi da attivare.",
      note: "Back office deve prevenire casino economico, legale e operativo.",
    },
    priorities: ["Vendite non fatturate", "Contratti/accessi incoerenti", "Rate o pagamenti critici"],
  },
};

export function getDepartmentRoom(id) {
  return DEPARTMENT_ROOMS[id] || DEPARTMENT_ROOMS.dashboard;
}
