export const DEPARTMENT_ROOMS = {
  dashboard: {
    id: "dashboard",
    label: "Dashboard",
    agent: {
      id: "luca",
      name: "Luca",
      role: "Amministratore Delegato AI",
      avatar: "/agents/luca.jpg",
      initials: "L",
      accent: "bg-slate-900 text-yellow-400",
      chat: "luca",
      prompt: "Fammi il briefing CEO di oggi e dimmi dove devo intervenire.",
    },
    metrics: [
      "Fatturato mese",
      "Partnership chiuse",
      "Partner attivi",
      "Partner bloccati",
      "Azioni per Claudio",
      "Reparto critico",
    ],
    priorities: ["Sblocca le decisioni rosse", "Controlla il reparto critico", "Verifica avanzamento partner e vendite"],
  },
  acquisizione: {
    id: "acquisizione",
    label: "Acquisizione",
    agent: {
      id: "luca",
      name: "Luca",
      role: "Coordinatore Acquisizione Evolution",
      avatar: "/agents/luca.jpg",
      initials: "L",
      chat: "luca",
      prompt: "Luca, dimmi quali messaggi stanno portando lead giusti e dove devo intervenire oggi su Acquisizione Evolution.",
    },
    metrics: [
      "Nuovi lead 7 giorni",
      "Lead qualificati",
      "Masterclass avviate",
      "8 Domande completate",
      "Ciak Start €499",
      "Blueprint acquistati",
      "Fonte migliore",
    ],
    priorities: [
      "20 nuovi contatti mirati",
      "Recuperi Blueprint e call",
      "Contenuto Claudio con CTA Ciak",
    ],
    prompts: [
      {
        label: "Priorita' del giorno",
        prompt: "Luca, dimmi quali contatti lavorare oggi per Acquisizione Evolution.",
      },
      {
        label: "Recuperi caldi",
        prompt: "Luca, trova chi ha cliccato checkout, completato le 8 Domande o acquistato Blueprint senza call.",
      },
      {
        label: "Contenuto acquisizione",
        prompt: "Andrea, prepara un contenuto Claudio che porti professionisti reali verso Ciak Blueprint.",
      },
    ],
  },
  vendite: {
    id: "vendite",
    label: "Vendite",
    agent: {
      id: "gaia",
      name: "Gaia",
      role: "Responsabile Vendite",
      avatar: "/agents/gaia.jpg",
      initials: "G",
      chat: "pending",
      prompt: "Gaia, dimmi dove stiamo perdendo partner pronti a comprare.",
    },
    metrics: [
      "Blueprint acquistati",
      "Call prenotate",
      "Call fatte",
      "Proposte inviate",
      "Ciak Start €499",
      "Partnership chiuse",
      "Valore trattative",
    ],
    priorities: ["Follow-up call fatte", "Proposte ferme", "Recuperi ad alto valore"],
  },
  delivery: {
    id: "delivery",
    label: "Delivery",
    agent: {
      id: "stefania",
      name: "Simona",
      role: "Responsabile Delivery",
      avatar: "/agents/stefania.jpg",
      initials: "S",
      chat: "stefania",
      prompt: "Simona, dimmi chi rischio di rallentare o perdere oggi.",
    },
    metrics: [
      "Partner attivi",
      "Partner per fase",
      "Fermi oltre soglia",
      "Output da approvare",
      "Materiali mancanti",
      "Prossimi live",
    ],
    priorities: ["Partner fermi", "Materiali da approvare", "Solleciti automatici"],
  },
  "casi-studio": {
    id: "casi-studio",
    label: "Casi studio",
    agent: {
      id: "andrea",
      name: "Andrea",
      role: "Responsabile Prova Sociale",
      avatar: "/agents/andrea.jpg",
      initials: "A",
      chat: "pending",
      prompt: "Andrea, quali risultati possiamo trasformare in fiducia per vendere meglio?",
    },
    metrics: [
      "Risultati documentabili",
      "Casi pronti",
      "Casi promettenti",
      "Asset mancanti",
      "Testimonianze",
      "Prima/dopo",
    ],
    priorities: ["Caso piu' forte", "Asset mancanti", "Partner da intervistare"],
  },
  "back-office": {
    id: "back-office",
    label: "Back office",
    agent: {
      id: "valentina",
      name: "Valentina",
      role: "Responsabile Back Office",
      avatar: "/agents/valentina.jpg",
      initials: "V",
      chat: "pending",
      prompt: "Valentina, dimmi cosa puo' bloccare incasso, contratto o serenita operativa.",
    },
    metrics: [
      "Incassi mese",
      "Scade oggi",
      "In ritardo",
      "Fatture da emettere",
      "Contratti firmati",
      "Pagamenti critici",
      "Servizi extra",
    ],
    priorities: ["Vendite non fatturate", "Contratti/accessi incoerenti", "Rate o pagamenti critici"],
  },
};

export function getDepartmentRoom(id) {
  return DEPARTMENT_ROOMS[id] || DEPARTMENT_ROOMS.dashboard;
}
