/**
 * Registro domande "La tua storia" (Esamina, Valentina).
 * Ogni domanda popola un campo del brand_profile (storia.*) e alimenta gli asset
 * narrativi (Hero Story, Chi Sono, script video, social, email).
 * Tutte obbligatorie; Valentina è sempre a supporto in chat.
 *
 * tipo: "lungo" (textarea) | "breve" (input) | "elenco" (uno per riga)
 */
export const STORIA_QUESTIONS = [
  { id: "S01", blocco: "Le tue origini", campo: "storia.origini.prima_di", tipo: "lungo", minChar: 30,
    domanda: "Prima di fare questo lavoro, di cosa ti occupavi?",
    hint: "Raccontalo come lo diresti a un amico: che lavoro facevi, com'era.",
    esempio: "Lavoravo in banca, allo sportello. Stipendio sicuro ma giornate tutte uguali." },
  { id: "S02", blocco: "Le tue origini", campo: "storia.origini.contesto", tipo: "lungo", minChar: 25,
    domanda: "Com'era la tua vita in quel periodo?",
    hint: "Il contesto: come stavi, cosa sentivi ogni giorno.",
    esempio: "Sempre di corsa, poca soddisfazione. Sentivo che non era la mia strada." },
  { id: "S03", blocco: "Le tue origini", campo: "storia.origini.autoritratto", tipo: "breve",
    domanda: "Come ti descriveresti com'eri allora, in poche parole?",
    hint: "Due o tre aggettivi sinceri.",
    esempio: "Insicuro, ma con tanta voglia di cambiare." },

  { id: "S04", blocco: "Il problema", campo: "storia.problema.difficolta", tipo: "lungo", minChar: 40,
    domanda: "Qual era la difficoltà più grande che vivevi?",
    hint: "Non un concetto: una scena concreta. Dov'eri, cosa succedeva.",
    esempio: "A fine mese non restava niente, pur lavorando dodici ore. Mi sentivo in trappola." },
  { id: "S05", blocco: "Il problema", campo: "storia.problema.cosa_non_funzionava", tipo: "lungo", minChar: 25,
    domanda: "Cosa non funzionava, per quanto ci provassi?",
    hint: "I tentativi che facevi e che non davano risultati.",
    esempio: "Provavo a fare più ore e più clienti, ma più correvo più restavo fermo." },
  { id: "S06", blocco: "Il problema", campo: "storia.problema.dolore", tipo: "lungo", minChar: 30,
    domanda: "Cosa ti faceva stare davvero male, in quel momento?",
    hint: "L'emozione vera, detta con parole tue.",
    esempio: "La sensazione di non valere abbastanza e di deludere la mia famiglia." },
  { id: "S07", blocco: "Il problema", campo: "storia.problema.desiderio", tipo: "breve",
    domanda: "Cosa volevi cambiare più di ogni altra cosa?",
    hint: "Una frase.",
    esempio: "Volevo finalmente sentirmi libero e padrone del mio tempo." },

  { id: "S08", blocco: "Il momento di svolta", campo: "storia.svolta.evento", tipo: "lungo", minChar: 40,
    domanda: "C'è stato un momento preciso che ha cambiato tutto? Raccontamelo.",
    hint: "Una scena: dov'eri, cosa è successo, cosa hai pensato.",
    esempio: "Una sera, dopo l'ennesimo no, ho capito che dovevo cambiare metodo, non lavorare di più." },
  { id: "S09", blocco: "Il momento di svolta", campo: "storia.svolta.decisione", tipo: "breve",
    domanda: "Quando hai deciso di cambiare strada?",
    hint: "Anche solo il periodo o l'occasione.",
    esempio: "L'inverno in cui ho perso il cliente più importante." },
  { id: "S10", blocco: "Il momento di svolta", campo: "storia.svolta.aiuto", tipo: "lungo", minChar: 20,
    domanda: "Qualcuno o qualcosa ti ha aiutato? Un mentore, un libro, una persona?",
    hint: "Chi o cosa ti ha aperto gli occhi.",
    esempio: "Un mentore mi ha insegnato a partire dal posizionamento, non dalle tattiche." },

  { id: "S11", blocco: "Il percorso", campo: "storia.percorso.ostacoli", tipo: "lungo", minChar: 25,
    domanda: "Quali ostacoli hai affrontato lungo la strada?",
    hint: "Le prove vere, anche scomode.",
    esempio: "Pochi soldi all'inizio, la paura di espormi, le critiche di chi non capiva." },
  { id: "S12", blocco: "Il percorso", campo: "storia.percorso.errori", tipo: "lungo", minChar: 25,
    domanda: "Quali errori hai fatto, che oggi racconteresti?",
    hint: "Gli sbagli ti rendono credibile, non debole.",
    esempio: "Ho abbassato i prezzi per paura, e ho attirato i clienti sbagliati." },
  { id: "S13", blocco: "Il percorso", campo: "storia.percorso.sacrifici", tipo: "lungo", minChar: 20,
    domanda: "Quali sacrifici hai dovuto fare?",
    hint: "Cosa hai messo in gioco.",
    esempio: "Serate e weekend per studiare, mentre gli altri uscivano." },
  { id: "S14", blocco: "Il percorso", campo: "storia.percorso.lezione", tipo: "lungo", minChar: 30,
    domanda: "Qual è la lezione più importante che hai imparato?",
    hint: "Il principio che oggi guida tutto.",
    esempio: "I risultati non arrivano lavorando di più, ma lavorando sulle cose giuste." },

  { id: "S15", blocco: "La trasformazione", campo: "storia.trasformazione.prova", tipo: "lungo", minChar: 30,
    domanda: "Quando hai capito che il tuo metodo funzionava davvero?",
    hint: "Il momento in cui hai visto la prova.",
    esempio: "Quando in tre mesi ho chiuso più clienti che nell'anno prima, senza inseguirli." },
  { id: "S16", blocco: "La trasformazione", campo: "storia.trasformazione.primo_successo", tipo: "lungo", minChar: 20,
    domanda: "Qual è stato il tuo primo vero successo?",
    hint: "Il primo risultato che ti ha fatto dire: funziona.",
    esempio: "Il primo cliente che mi ha pagato in anticipo, convinto solo dal mio messaggio." },
  { id: "S17", blocco: "La trasformazione", campo: "storia.trasformazione.cliente_simbolo", tipo: "lungo", minChar: 25,
    domanda: "C'è un cliente che non dimenticherai mai? Cosa è cambiato per lui o lei?",
    hint: "Una storia di trasformazione concreta.",
    esempio: "Una mamma che da zero clienti è arrivata a vivere del suo lavoro in sei mesi." },

  { id: "S18", blocco: "Oggi", campo: "storia.oggi.perche", tipo: "lungo", minChar: 25,
    domanda: "Perché fai questo lavoro, oggi?",
    hint: "La ragione profonda, oltre i soldi.",
    esempio: "Perché so cosa significa sentirsi bloccati, e voglio evitarlo agli altri." },
  { id: "S19", blocco: "Oggi", campo: "storia.oggi.missione", tipo: "breve",
    domanda: "Qual è la tua missione, in una frase?",
    hint: "Cosa vuoi rendere possibile per le persone che aiuti.",
    esempio: "Aiutare i professionisti a vivere del proprio valore, non delle proprie ore." },
  { id: "S20", blocco: "Oggi", campo: "storia.oggi.impatto", tipo: "lungo", minChar: 20,
    domanda: "Che impatto vuoi lasciare nelle persone che aiuti?",
    hint: "Come vuoi che si sentano e cosa vuoi che ottengano.",
    esempio: "Voglio che ritrovino fiducia e che costruiscano qualcosa di loro." },
  { id: "S21", blocco: "Oggi", campo: "storia.oggi.valori", tipo: "elenco",
    domanda: "Quali 3 valori guidano ogni tua decisione?",
    hint: "Uno per riga.",
    esempio: "Onestà\nConcretezza\nRispetto" },
];
